In [1]:
import numpy as np
import scanpy as sc
from scipy import sparse

In [31]:
import model
import data_proc_methods as dpm

In [33]:
adata,enc = dpm.load_data("subchunk1_1.h5ad")

In [37]:
adata.obs

ROIGroup   ROIGroupCoarse     ROIGroupFine  \
CellID                                                                         
10X276_2:TCCGATCAGTCTGCGC  Cerebral cortex  Cerebral cortex  Cerebral cortex   
10X172_8:AACGTCACACAAGCTT  Cerebral cortex  Cerebral cortex  Cerebral cortex   
10X160_8:AACCCAAGTATCAGGG  Cerebral cortex  Cerebral cortex  Cerebral cortex   
10X220_8:TTACTGTAGATGCTTC  Cerebral nuclei  Cerebral nuclei        Claustrum   
10X350_3:GACTATGTCAGTGTGT        Hindbrain       Cerebellum       Cerebellum   
...                                    ...              ...              ...   
10X330_4:TTCATTGTCGGTAGAG  Cerebral nuclei  Cerebral nuclei  Basal forebrain   
10X276_7:TTGTTCATCCCTCAAC  Cerebral cortex  Cerebral cortex  Cerebral cortex   
10X276_6:GTCTGTCCAGTGGGTA  Cerebral cortex  Cerebral cortex  Cerebral cortex   
10X145_7:ACCATTTCACCCAAGC  Cerebral nuclei  Cerebral nuclei     Basal nuclei   
10X203_1:CTGAGGCAGCTCTTCC         Thalamus         Thalamus         Thalamus   

                                     roi organism_ontology_term_id  \
CellID                                                               
10X276_2:TCCGATCAGTCTGCGC      Human Pir            NCBITaxon:9606   
10X172_8:AACGTCACACAAGCTT      Human A14            NCBITaxon:9606   
10X160_8:AACCCAAGTATCAGGG      Human M1C            NCBITaxon:9606   
10X220_8:TTACTGTAGATGCTTC      Human Cla            NCBITaxon:9606   
10X350_3:GACTATGTCAGTGTGT     Human CbDN            NCBITaxon:9606   
...                                  ...                       ...   
10X330_4:TTCATTGTCGGTAGAG      Human SEP            NCBITaxon:9606   
10X276_7:TTGTTCATCCCTCAAC      Human A1C            NCBITaxon:9606   
10X276_6:GTCTGTCCAGTGGGTA  Human A44-A45            NCBITaxon:9606   
10X145_7:ACCATTTCACCCAAGC      Human GPe            NCBITaxon:9606   
10X203_1:CTGAGGCAGCTCTTCC       Human CM            NCBITaxon:9606   

                          disease_ontology_term_id  \
CellID                                               
10X276_2:TCCGATCAGTCTGCGC             PATO:0000461   
10X172_8:AACGTCACACAAGCTT             PATO:0000461   
10X160_8:AACCCAAGTATCAGGG             PATO:0000461   
10X220_8:TTACTGTAGATGCTTC             PATO:0000461   
10X350_3:GACTATGTCAGTGTGT             PATO:0000461   
...                                            ...   
10X330_4:TTCATTGTCGGTAGAG             PATO:0000461   
10X276_7:TTGTTCATCCCTCAAC             PATO:0000461   
10X276_6:GTCTGTCCAGTGGGTA             PATO:0000461   
10X145_7:ACCATTTCACCCAAGC             PATO:0000461   
10X203_1:CTGAGGCAGCTCTTCC             PATO:0000461   

                          self_reported_ethnicity_ontology_term_id  \
CellID                                                               
10X276_2:TCCGATCAGTCTGCGC                                  unknown   
10X172_8:AACGTCACACAAGCTT                                  unknown   
10X160_8:AACCCAAGTATCAGGG                                  unknown   
10X220_8:TTACTGTAGATGCTTC                                  unknown   
10X350_3:GACTATGTCAGTGTGT                                  unknown   
...                                                            ...   
10X330_4:TTCATTGTCGGTAGAG                                  unknown   
10X276_7:TTGTTCATCCCTCAAC                                  unknown   
10X276_6:GTCTGTCCAGTGGGTA                                  unknown   
10X145_7:ACCATTTCACCCAAGC                                  unknown   
10X203_1:CTGAGGCAGCTCTTCC                                  unknown   

                          assay_ontology_term_id sex_ontology_term_id  \
CellID                                                                  
10X276_2:TCCGATCAGTCTGCGC            EFO:0009922         PATO:0000384   
10X172_8:AACGTCACACAAGCTT            EFO:0009922         PATO:0000384   
10X160_8:AACCCAAGTATCAGGG            EFO:0009922         PATO:0000383   
10X220_8:TTACTGTAGATGCTTC            EFO:0009922         PATO:0000384   
10X350_3:GACTATGTCAGTGTGT     

In [41]:
from importlib import reload

In [94]:
reload(model)

<module 'model' from '/Users/jdfld/Documents/Programmering/KEX/model.py'>

In [65]:
auto = model.AutoEncoder(adata.var['Gene'])

In [53]:
aloader = dpm.create_annloader(adata)

In [66]:
model.train_nn(aloader,enc,auto,label_type='AutoEnc',epochs=5)

Epoch:1, Loss:0.0902
Epoch:2, Loss:0.0703
Epoch:3, Loss:0.0652
Epoch:4, Loss:0.0560
Epoch:5, Loss:0.0631


In [68]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
from sklearn.

In [83]:
rfc = RandomForestClassifier()

In [76]:
import torch

In [ ]:
adata.X.todense()

In [85]:
rfc = model.SimpleModel(model_type='rfc')

In [78]:
torch.FloatTensor(adata.X.todense())

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [97]:
adata.obs['supercluster_term'].values.reshape(-1,1).shape

(42115, 1)

In [99]:
encoded = auto.encode(torch.FloatTensor(adata.X.todense()))
rfc.fit(encoded.detach().numpy(),adata.obs['supercluster_term'].values.reshape(-1,1))

0.9997625549091772

In [101]:
bdata,_ = dpm.load_data('subchunk1_2.h5ad')

In [ ]:
bencoded = auto.encode(torch.FloatTensor(bdata.X.todense()))

In [ ]:
rfc.predict(bencoded.detach().numpy(),bdata.obs['supercluster_term'].values.reshape(-1,1))

In [39]:
model.BasicNeuralNetwork(adata.var['Gene'],adata.obs['supercluster_term'].cat.categories)

BasicNeuralNetwork(
  (model): Sequential(
    (0): Linear(in_features=59480, out_features=512, bias=True)
    (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): LeakyReLU(negative_slope=0.01)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=512, out_features=512, bias=True)
    (5): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): LeakyReLU(negative_slope=0.01)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=512, out_features=512, bias=True)
    (9): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (10): LeakyReLU(negative_slope=0.01)
    (11): Linear(in_features=512, out_features=31, bias=True)
    (12): Sigmoid()
  )
)

In [2]:
adata = sc.read_h5ad("subchunk1_1.h5ad")
bdata = sc.read_h5ad("thalamic_complex24327.h5ad")
print(adata.shape)
print(bdata.shape)

(42115, 59480)
(24327, 59357)


In [7]:
cdata = sc.read_h5ad('unknown.h5ad')

In [24]:
set(sorted(cdata.var['gene_name']))

{'Synpr',
 'Lrat',
 'Tshz2',
 'Cdh20',
 'D430036J16Rik',
 'Tmem215',
 'A730046J19Rik',
 'Greb1',
 'Rasgrp2',
 'Trabd2b',
 'Vit',
 'Slc30a3',
 'Cd44',
 'Palld',
 'Prom1',
 'Sh3rf2',
 'Irx5',
 'Otx2',
 'Smoc2',
 'Igfbp4',
 'Trpc5',
 'Lhx6',
 'Gxylt2',
 'Ntn1',
 'Cngb3',
 'Slit2',
 'Mmel1',
 'Itgad',
 'C230014O12Rik',
 'Adad1',
 'Dlx1as',
 'Pla2g7',
 'Dlx6',
 'Adamts16',
 'Cnmd',
 'Emx2os',
 'Ermn',
 'Smpdl3b',
 'Unc13c',
 'Plscr4',
 'Cckar',
 'Pim1',
 'Syt6',
 'Elfn1',
 'Slc18a2',
 'Cntnap3',
 'Col26a1',
 'Hmx2',
 'Crhbp',
 'Pou3f3',
 'Kcnh3',
 'Vegfc',
 'Sox14',
 'Kcnj4',
 'Zic1',
 'Gzmk',
 'Lama4',
 'Pdzrn3',
 'Kcnip1',
 'Ccdc141',
 'Ets1',
 'Gja1',
 'Matn2',
 'Nhlh2',
 'Chrna6',
 'Robo3',
 'Sema5b',
 'Otp',
 'Scn5a',
 'Ramp3',
 'Lsp1',
 'Apex1',
 'Casr',
 'Epha4',
 'Adam18',
 'Klk8',
 'Ntng1',
 'Adamts9',
 'Ret',
 'Slitrk6',
 'St14',
 'Mrpl16',
 'Bmpr1b',
 'Gabre',
 'Coro6',
 'Drd1',
 'Fgf1',
 '4921539H07Rik',
 'Npr3',
 'Ppp1r1b',
 'Tafa1',
 '4930509J09Rik',
 'Stac2',
 'Kcng1',
 '4930

In [30]:
set(sorted(adata.var['Gene'])).intersection(set(sorted(cdata.var['gene_name'])))

{'C7'}

In [5]:
bdata

AnnData object with n_obs × n_vars = 24327 × 59357
    obs: 'roi', 'organism_ontology_term_id', 'disease_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'assay_ontology_term_id', 'sex_ontology_term_id', 'development_stage_ontology_term_id', 'donor_id', 'suspension_type', 'dissection', 'fraction_mitochondrial', 'fraction_unspliced', 'cell_cycle_score', 'total_genes', 'total_UMIs', 'sample_id', 'supercluster_term', 'cluster_id', 'subcluster_id', 'cell_type_ontology_term_id', 'tissue_ontology_term_id', 'is_primary_data', 'tissue_type', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'Biotype', 'Chromosome', 'End', 'Gene', 'Start', 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length'
    uns: 'batch_condition', 'citation', 'schema_reference', 'schema_version', 'title'
    obsm: 'X_UMAP', 'X_tSNE'

In [9]:
bdata.obs['cell_type_ontology_term_id']

CellID
10X389_6:CTCAACCCAGAGTAAT    CL:0000540
10X389_5:TATATCCCATACACCA    CL:0000540
10X377_1:CGCGTGAAGCAACCAG    CL:0000540
10X377_2:CAACCTCCAATTGCGT    CL:0000540
10X377_1:GAAATGAGTGTATACC    CL:0000540
                                ...    
10X389_5:TCGGGTGCAAGGTCAG    CL:0000738
10X389_5:TATCTGTGTATGGTTC    CL:0000738
10X389_5:GATCAGTAGAGCTTTC    CL:0000738
10X377_2:TTTATGCGTCTTCCGT    CL:0000738
10X389_5:TTCGGTCGTATCGCTA    CL:0000738
Name: cell_type_ontology_term_id, Length: 24327, dtype: category
Categories (11, object): ['CL:0000057', 'CL:0000065', 'CL:0000115', 'CL:0000127', ..., 'CL:0000669', 'CL:0000738', 'CL:0000878', 'CL:0002453']

In [3]:
cdata = sc.read_h5ad('data_chunk1.h5ad')

KeyboardInterrupt: 

In [21]:
import Encoder

In [22]:
from importlib import reload

In [35]:
reload(Encoder)

<module 'Encoder' from '/Users/jdfld/Documents/Programmering/KEX/Encoder.py'>

In [36]:
autoencoder = Encoder.Encoder(bdata.var['Gene'])

In [6]:
import torch

In [37]:
type(bdata.X)

scipy.sparse._csr.csr_matrix

In [38]:
i = 0
for j in range(bdata.X.shape[0]):
    a = bdata.X[j].toarray()
    print(max(a))
    print(a.shape)
    i += 1
    if i == 5:
        break

[1. 1. 1. ... 0. 0. 0.]
(1, 59357)
[0. 0. 0. ... 0. 0. 0.]
(1, 59357)
[0. 0. 0. ... 0. 0. 0.]
(1, 59357)
[0. 0. 0. ... 0. 0. 0.]
(1, 59357)
[0. 0. 0. ... 0. 0. 0.]
(1, 59357)


In [39]:
optimizer = torch.optim.Adam(autoencoder.parameters(),lr=autoencoder.lr,weight_decay=1e-5)
criterion = torch.nn.MSELoss()

In [40]:
Encoder.Encoder.train(data=bdata.X,model = autoencoder,optimizer=optimizer,criterion=criterion,epochs=10)

w
w
w
w
Epoch:1, Loss:0.2638
w
w
w
w
Epoch:2, Loss:0.2626
w
w
w
w
Epoch:3, Loss:0.2600
w
w
w
w
Epoch:4, Loss:0.2546
w
w
w
w
Epoch:5, Loss:0.2504
w
w
w
w
Epoch:6, Loss:0.2416
w
w
w
w
Epoch:7, Loss:0.2326
w
w
w
w
Epoch:8, Loss:0.2204
w
w
w
w
Epoch:9, Loss:0.2067
w
w
w
w
Epoch:10, Loss:0.1918


In [13]:
cdata.var

Empty DataFrame
Columns: []
Index: [Cas9, EGFP, ENSG00000000003.15, ENSG00000000005.6, ENSG00000000419.13, ENSG00000000457.14, ENSG00000000460.17, ENSG00000000938.13, ENSG00000000971.16, ENSG00000001036.14, ENSG00000001084.13, ENSG00000001167.14, ENSG00000001460.18, ENSG00000001461.17, ENSG00000001497.17, ENSG00000001561.7, ENSG00000001617.12, ENSG00000001626.16, ENSG00000001629.10, ENSG00000001630.17, ENSG00000001631.16, ENSG00000002016.18, ENSG00000002079.14, ENSG00000002330.14, ENSG00000002549.12, ENSG00000002586.20, ENSG00000002586.20_PAR_Y, ENSG00000002587.10, ENSG00000002726.21, ENSG00000002745.13, ENSG00000002746.15, ENSG00000002822.15, ENSG00000002834.18, ENSG00000002919.15, ENSG00000002933.9, ENSG00000003056.8, ENSG00000003096.14, ENSG00000003137.8, ENSG00000003147.19, ENSG00000003249.14, ENSG00000003393.15, ENSG00000003400.15, ENSG00000003402.20, ENSG00000003436.16, ENSG00000003509.16, ENSG00000003756.17, ENSG00000003987.14, ENSG00000003989.18, ENSG00000004059.11, ENSG00000004139.14, ENSG00000004142.12, ENSG00000004399.13, ENSG00000004455.17, ENSG00000004468.13, ENSG00000004478.8, ENSG00000004487.17, ENSG00000004534.15, ENSG00000004660.15, ENSG00000004700.16, ENSG00000004766.17, ENSG00000004776.13, ENSG00000004777.18, ENSG00000004779.10, ENSG00000004799.8, ENSG00000004809.14, ENSG00000004838.14, ENSG00000004846.16, ENSG00000004848.8, ENSG00000004864.14, ENSG00000004866.21, ENSG00000004897.12, ENSG00000004939.15, ENSG00000004948.16, ENSG00000004961.15, ENSG00000004975.12, ENSG00000005001.10, ENSG00000005007.13, ENSG00000005020.13, ENSG00000005022.6, ENSG00000005059.16, ENSG00000005073.6, ENSG00000005100.13, ENSG00000005102.14, ENSG00000005108.16, ENSG00000005156.12, ENSG00000005175.10, ENSG00000005187.12, ENSG00000005189.19, ENSG00000005194.15, ENSG00000005206.17, ENSG00000005238.20, ENSG00000005243.10, ENSG00000005249.13, ENSG00000005302.19, ENSG00000005339.15, ENSG00000005379.17, ENSG00000005381.8, ENSG00000005421.9, ENSG00000005436.14, ENSG00000005448.17, ...]

[59480 rows x 0 columns]

In [8]:
adata.var

Empty DataFrame
Columns: []
Index: [Cas9, EGFP, ENSG00000000003.15, ENSG00000000005.6, ENSG00000000419.13, ENSG00000000457.14, ENSG00000000460.17, ENSG00000000938.13, ENSG00000000971.16, ENSG00000001036.14, ENSG00000001084.13, ENSG00000001167.14, ENSG00000001460.18, ENSG00000001461.17, ENSG00000001497.17, ENSG00000001561.7, ENSG00000001617.12, ENSG00000001626.16, ENSG00000001629.10, ENSG00000001630.17, ENSG00000001631.16, ENSG00000002016.18, ENSG00000002079.14, ENSG00000002330.14, ENSG00000002549.12, ENSG00000002586.20, ENSG00000002586.20_PAR_Y, ENSG00000002587.10, ENSG00000002726.21, ENSG00000002745.13, ENSG00000002746.15, ENSG00000002822.15, ENSG00000002834.18, ENSG00000002919.15, ENSG00000002933.9, ENSG00000003056.8, ENSG00000003096.14, ENSG00000003137.8, ENSG00000003147.19, ENSG00000003249.14, ENSG00000003393.15, ENSG00000003400.15, ENSG00000003402.20, ENSG00000003436.16, ENSG00000003509.16, ENSG00000003756.17, ENSG00000003987.14, ENSG00000003989.18, ENSG00000004059.11, ENSG00000004139.14, ENSG00000004142.12, ENSG00000004399.13, ENSG00000004455.17, ENSG00000004468.13, ENSG00000004478.8, ENSG00000004487.17, ENSG00000004534.15, ENSG00000004660.15, ENSG00000004700.16, ENSG00000004766.17, ENSG00000004776.13, ENSG00000004777.18, ENSG00000004779.10, ENSG00000004799.8, ENSG00000004809.14, ENSG00000004838.14, ENSG00000004846.16, ENSG00000004848.8, ENSG00000004864.14, ENSG00000004866.21, ENSG00000004897.12, ENSG00000004939.15, ENSG00000004948.16, ENSG00000004961.15, ENSG00000004975.12, ENSG00000005001.10, ENSG00000005007.13, ENSG00000005020.13, ENSG00000005022.6, ENSG00000005059.16, ENSG00000005073.6, ENSG00000005100.13, ENSG00000005102.14, ENSG00000005108.16, ENSG00000005156.12, ENSG00000005175.10, ENSG00000005187.12, ENSG00000005189.19, ENSG00000005194.15, ENSG00000005206.17, ENSG00000005238.20, ENSG00000005243.10, ENSG00000005249.13, ENSG00000005302.19, ENSG00000005339.15, ENSG00000005379.17, ENSG00000005381.8, ENSG00000005421.9, ENSG00000005436.14, ENSG00000005448.17, ...]

[59480 rows x 0 columns]

In [6]:
bdata.var

Biotype Chromosome        End        Gene      Start  \
ensembl_ids                                                            
ENSG00000235615     n/a       chr2  131979873  AJ239322.1  131964731   
ENSG00000262185     n/a      chr16    3950586   LINC02861    3930806   
ENSG00000228669     n/a      chr13   62796714   LINC00448   62672285   
ENSG00000287243     n/a      chr12    3492819    THCAT155    3483714   
ENSG00000072163     n/a       chr2  127681786       LIMS2  127638381   
...                 ...        ...        ...         ...        ...   
ENSG00000261490     n/a       chr4   10073019  AC005674.2   10068089   
ENSG00000183977     n/a       chr3   20012267       PP2D1   19979961   
ENSG00000271425     n/a       chr1  146229000      NBPF10  146064711   
ENSG00000164430     n/a       chr6   73452297        CGAS   73413515   
ENSG00000287825     n/a       chr6   42929457  AL035587.2   42928287   

                 feature_is_filtered   feature_name feature_reference  \
ensembl_ids                                                             
ENSG00000235615                False     AJ239322.1    NCBITaxon:9606   
ENSG00000262185                False      LINC02861    NCBITaxon:9606   
ENSG00000228669                False      LINC00448    NCBITaxon:9606   
ENSG00000287243                False       THCAT155    NCBITaxon:9606   
ENSG00000072163                False          LIMS2    NCBITaxon:9606   
...                              ...            ...               ...   
ENSG00000261490                False  RP11-448G15.3    NCBITaxon:9606   
ENSG00000183977                False          PP2D1    NCBITaxon:9606   
ENSG00000271425                False         NBPF10    NCBITaxon:9606   
ENSG00000164430                False           CGAS    NCBITaxon:9606   
ENSG00000287825                False   RP3-475N16.9    NCBITaxon:9606   

                feature_biotype feature_length  
ensembl_ids                                     
ENSG00000235615            gene           2209  
ENSG00000262185            gene           2721  
ENSG00000228669            gene           1637  
ENSG00000287243            gene           6521  
ENSG00000072163            gene           8731  
...                         ...            ...  
ENSG00000261490            gene           3510  
ENSG00000183977            gene           2494  
ENSG00000271425            gene          14362  
ENSG00000164430            gene           4174  
ENSG00000287825            gene            653  

[59357 rows x 10 columns]